[env:esp32-devkit]
platform = espressif32
board = esp32dev
framework = espidf
monitor_filters=esp32_exception_decoder
upload_speed=921600
monitor_speed=115200
upload_port=COM23
monitor_port=COM23
extra_scripts = pre:luthor_extra.py