// <auto-generated/>
// Shared runtime for Luthor lexers. Luthor.Generator emits this file once per assembly; every
// generated lexer in the assembly uses the same matcher and windows, and only carries its own
// DFA table(s).
#nullable enable
#pragma warning disable

namespace Luthor
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Runtime.CompilerServices;
    using System.Text;

    /// <summary>
    /// Declares one lexer rule. Rules are tried in declaration order: when two rules match the
    /// same (longest) length, the one declared first wins. <paramref name="name"/> becomes a
    /// <c>public const int</c> symbol id on the lexer class.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
    internal sealed class RuleAttribute : Attribute
    {
        /// <param name="name">Symbol name; must be a valid C# identifier.</param>
        /// <param name="pattern">Regular expression, or literal text when <paramref name="isLiteral"/> is true.</param>
        /// <param name="isLiteral">Match <paramref name="pattern"/> exactly, with no regex metacharacters.</param>
        public RuleAttribute(string name, string pattern, bool isLiteral) { Name = name; Pattern = pattern; IsLiteral = isLiteral; }
        public RuleAttribute(string name, string pattern) : this(name, pattern, false) { }
        public string Name { get; }
        public string Pattern { get; }
        public bool IsLiteral { get; }
    }

    /// <summary>Optional lexer-wide settings for a class that carries <see cref="RuleAttribute"/>s.</summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal sealed class LexerAttribute : Attribute
    {
        /// <summary>
        /// Add a final catch-all <c>ERROR</c> rule so every unit of input lands in some token
        /// (default true). When false, input no rule matches is returned one unit at a time
        /// with symbol -1.
        /// </summary>
        public bool ErrorRule { get; set; } = true;

        /// <summary>
        /// When set, also generate <c>Tokenize(byte[])</c> and <c>Tokenize(Stream)</c> overloads
        /// that run a second DFA directly over bytes in this encoding: "UTF-8", "UTF-16" /
        /// "UTF-16LE" / "UTF-16BE", "UTF-32" / "UTF-32LE" / "UTF-32BE", or any single-byte code
        /// page by name or number ("latin1", "windows-1252", "437", ...).
        /// </summary>
        public string? Encoding { get; set; }

        /// <summary>
        /// When set, also supports unicode characters in character classes, e.g. <c>[[:L:]]</c> for letters, <c>[[:Lu:]]</c> for uppercase letters, etc.
        /// </summary>
        public bool Unicode { get; set; } = false;
    }

    /// <summary>Input encoding for the byte-level tokenizers: how code units are laid out in bytes.</summary>
    internal sealed class UnitEncoding
    {
        public UnitEncoding(Encoding encoding, int unitSize, bool bigEndian)
        {
            Encoding = encoding;
            UnitSize = unitSize;
            BigEndian = bigEndian;
            Preamble = encoding.GetPreamble();
        }

        /// <summary>Used to decode token text.</summary>
        public Encoding Encoding { get; }
        /// <summary>Bytes per code unit: 1, 2 or 4.</summary>
        public int UnitSize { get; }
        public bool BigEndian { get; }
        /// <summary>Byte order mark skipped at the start of input, if present.</summary>
        public byte[] Preamble { get; }

        public static Encoding CodePage(string name)
        {
            System.Text.Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            return int.TryParse(name, NumberStyles.None, CultureInfo.InvariantCulture, out int page)
                ? System.Text.Encoding.GetEncoding(page)
                : System.Text.Encoding.GetEncoding(name);
        }
    }

    // A source of code units for the matcher. Implemented by small structs so the JIT
    // specializes Match<T> for each input kind (no interface dispatch in the inner loop).
    internal interface IUnitSource
    {
        /// <summary>Code unit at offset from the start of the current token, or -1 at end of input.</summary>
        int Peek(int offset);
    }

    internal static class LexerRuntime
    {
        // Flat table layout (see Luthor's Compiler.cs):
        //   dfa[0]  newline code unit (for ^ and $), then per state:
        //   accept, bol, eol, n, n x (min, max, target)

        /// <summary>Longest match at the start of <paramref name="text"/>. Returns (symbol or -1, length in units).</summary>
        internal static (int Token, int Length) Match<T>(int[] dfa, ref T text, bool atLineStart) where T : struct, IUnitSource
        {
            int state = 1, accept = -1, length = 0, i = 0;
            bool bol = atLineStart;
            while (true)
            {
                int c = text.Peek(i);                                                          // -1 at end of input
                if (bol && dfa[state + 1] != -1) state = dfa[state + 1];                       // ^
                if ((c == -1 || c == dfa[0]) && dfa[state + 2] != -1) state = dfa[state + 2]; // $
                if (dfa[state] != -1) { accept = dfa[state]; length = i; }
                if (c == -1) break;
                int next = -1, r = state + 4;                                                  // (min, max, target) triples, sorted
                for (int k = 0; k < dfa[state + 3] && c >= dfa[r]; k++, r += 3)
                    if (c <= dfa[r + 1]) { next = dfa[r + 2]; break; }
                if (next == -1) break;
                state = next;
                bol = c == dfa[0];
                i++;
            }
            return (accept, length);
        }

        // ---------------------------------------------------------------- string

        internal static IEnumerable<(long Position, int Symbol, string Text)> Tokenize(int[] dfa, string text)
        {
            if (text is null) throw new ArgumentNullException(nameof(text));
            return TokenizeString(dfa, text);
        }

        static IEnumerable<(long Position, int Symbol, string Text)> TokenizeString(int[] dfa, string text)
        {
            for (int pos = 0; pos < text.Length;)
            {
                var src = new StringSource(text, pos);
                bool atLineStart = pos == 0 || text[pos - 1] == dfa[0];
                var (tok, len) = Match(dfa, ref src, atLineStart);
                if (len == 0) { tok = -1; len = 1; }  // nothing matched (or only an empty match): skip one unit
                yield return (pos, tok, text.Substring(pos, len));
                pos += len;
            }
        }

        struct StringSource : IUnitSource
        {
            readonly string _text; readonly int _pos;
            public StringSource(string text, int pos) { _text = text; _pos = pos; }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public int Peek(int offset) => _pos + offset < _text.Length ? _text[_pos + offset] : -1;
        }

        // ---------------------------------------------------------------- TextReader

        internal static IEnumerable<(long Position, int Symbol, string Text)> Tokenize(int[] dfa, TextReader reader)
        {
            if (reader is null) throw new ArgumentNullException(nameof(reader));
            return TokenizeReader(dfa, reader);
        }

        static IEnumerable<(long Position, int Symbol, string Text)> TokenizeReader(int[] dfa, TextReader reader)
        {
            var window = new CharWindow(reader);
            long pos = 0;
            bool atLineStart = true;
            while (window.Peek(0) != -1)
            {
                var src = new CharWindowSource(window);
                var (tok, len) = Match(dfa, ref src, atLineStart);
                if (len == 0) { tok = -1; len = 1; }
                atLineStart = window.Peek(len - 1) == dfa[0];
                string s = window.Take(len);
                yield return (pos, tok, s);
                pos += len;
            }
        }

        struct CharWindowSource : IUnitSource
        {
            readonly CharWindow _w;
            public CharWindowSource(CharWindow w) => _w = w;
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public int Peek(int offset) => _w.Peek(offset);
        }

        // ---------------------------------------------------------------- byte[]

        internal static IEnumerable<(long Position, int Symbol, string Text)> Tokenize(int[] dfa, byte[] data, UnitEncoding encoding, int errorSymbol)
        {
            if (data is null) throw new ArgumentNullException(nameof(data));
            return TokenizeBytes(dfa, data, encoding, errorSymbol);
        }

        static IEnumerable<(long Position, int Symbol, string Text)> TokenizeBytes(int[] dfa, byte[] data, UnitEncoding enc, int errorSymbol)
        {
            int unit = enc.UnitSize;
            int pos = StartsWith(data, enc.Preamble) ? enc.Preamble.Length : 0;
            bool atLineStart = true;
            while (pos < data.Length)
            {
                var src = new ByteSource(data, pos, unit, enc.BigEndian);
                if (src.Peek(0) == -1)
                {
                    // fewer than UnitSize bytes left: a truncated code unit
                    yield return (pos, errorSymbol, enc.Encoding.GetString(data, pos, data.Length - pos));
                    yield break;
                }
                var (tok, len) = Match(dfa, ref src, atLineStart);
                if (len == 0) { tok = -1; len = 1; }
                atLineStart = src.Peek(len - 1) == dfa[0];
                int bytes = len * unit;
                yield return (pos, tok, enc.Encoding.GetString(data, pos, bytes));
                pos += bytes;
            }
        }

        static bool StartsWith(byte[] data, byte[] prefix)
        {
            if (prefix.Length == 0 || data.Length < prefix.Length) return false;
            for (int k = 0; k < prefix.Length; k++) if (data[k] != prefix[k]) return false;
            return true;
        }

        struct ByteSource : IUnitSource
        {
            readonly byte[] _data; readonly int _pos, _unit; readonly bool _bigEndian;
            public ByteSource(byte[] data, int pos, int unit, bool bigEndian) { _data = data; _pos = pos; _unit = unit; _bigEndian = bigEndian; }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public int Peek(int offset)
            {
                long o = _pos + (long)offset * _unit;
                return o + _unit <= _data.Length ? ReadUnit(_data, (int)o, _unit, _bigEndian) : -1;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static int ReadUnit(byte[] b, int o, int unit, bool bigEndian)
        {
            switch (unit)
            {
                case 1: return b[o];
                case 2: return bigEndian ? b[o] << 8 | b[o + 1] : b[o] | b[o + 1] << 8;
                default:
                    uint u = bigEndian
                        ? (uint)b[o] << 24 | (uint)b[o + 1] << 16 | (uint)b[o + 2] << 8 | b[o + 3]
                        : b[o] | (uint)b[o + 1] << 8 | (uint)b[o + 2] << 16 | (uint)b[o + 3] << 24;
                    return u > int.MaxValue ? int.MaxValue : (int)u;   // never collide with -1 (end of input)
            }
        }

        // ---------------------------------------------------------------- Stream

        internal static IEnumerable<(long Position, int Symbol, string Text)> Tokenize(int[] dfa, Stream stream, UnitEncoding encoding, int errorSymbol)
        {
            if (stream is null) throw new ArgumentNullException(nameof(stream));
            return TokenizeStream(dfa, stream, encoding, errorSymbol);
        }

        static IEnumerable<(long Position, int Symbol, string Text)> TokenizeStream(int[] dfa, Stream stream, UnitEncoding enc, int errorSymbol)
        {
            var window = new ByteWindow(stream);
            int unit = enc.UnitSize;
            long pos = 0;
            if (window.StartsWith(enc.Preamble)) { window.Skip(enc.Preamble.Length); pos = enc.Preamble.Length; }
            bool atLineStart = true;
            while (window.PeekByte(0) != -1)
            {
                var src = new ByteWindowSource(window, unit, enc.BigEndian);
                if (src.Peek(0) == -1)
                {
                    int rest = window.Available;
                    yield return (pos, errorSymbol, window.Take(rest, enc.Encoding));
                    yield break;
                }
                var (tok, len) = Match(dfa, ref src, atLineStart);
                if (len == 0) { tok = -1; len = 1; }
                atLineStart = src.Peek(len - 1) == dfa[0];
                int bytes = len * unit;
                yield return (pos, tok, window.Take(bytes, enc.Encoding));
                pos += bytes;
            }
        }

        struct ByteWindowSource : IUnitSource
        {
            readonly ByteWindow _w; readonly int _unit; readonly bool _bigEndian;
            public ByteWindowSource(ByteWindow w, int unit, bool bigEndian) { _w = w; _unit = unit; _bigEndian = bigEndian; }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public int Peek(int offset) => _unit == 1 ? _w.PeekByte(offset) : _w.PeekUnit(offset, _unit, _bigEndian);
        }
    }

    // A growable window over a TextReader. Index 0 is the start of the current token.
    // Chars are read on demand; Take() consumes from the front. The buffer only grows
    // when a single token (plus its lookahead/overrun) doesn't fit.
    internal sealed class CharWindow
    {
        readonly TextReader _reader;
        char[] _buf;
        int _start, _end;
        bool _eof;

        public CharWindow(TextReader reader, int capacity = 4096)
        {
            _reader = reader ?? throw new ArgumentNullException(nameof(reader));
            _buf = new char[capacity];
        }

        /// <summary>Char at offset from the token start, or -1 at end of input.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Peek(int offset)
            => _start + offset < _end ? _buf[_start + offset] : PeekSlow(offset);

        [MethodImpl(MethodImplOptions.NoInlining)]
        int PeekSlow(int offset)
        {
            while (_start + offset >= _end)
            {
                if (_eof) return -1;
                Fill();
            }
            return _buf[_start + offset];
        }

        void Fill()
        {
            if (_end == _buf.Length)
            {
                if (_start == 0)
                {
                    Array.Resize(ref _buf, _buf.Length * 2);
                }
                else
                {
                    int count = _end - _start;
                    Array.Copy(_buf, _start, _buf, 0, count);   // overlap-safe
                    _start = 0;
                    _end = count;
                }
            }
            int n = _reader.Read(_buf, _end, _buf.Length - _end);
            if (n == 0) _eof = true;
            else _end += n;
        }

        public string Take(int length)
        {
            string s = new string(_buf, _start, length);
            _start += length;
            return s;
        }
    }

    // The byte counterpart of CharWindow, over a Stream.
    internal sealed class ByteWindow
    {
        readonly Stream _stream;
        byte[] _buf;
        int _start, _end;
        bool _eof;

        public ByteWindow(Stream stream, int capacity = 4096)
        {
            _stream = stream ?? throw new ArgumentNullException(nameof(stream));
            _buf = new byte[capacity];
        }

        /// <summary>Bytes currently buffered past the token start.</summary>
        public int Available => _end - _start;

        /// <summary>Byte at offset from the token start, or -1 at end of input.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int PeekByte(int offset)
            => _start + offset < _end ? _buf[_start + offset] : PeekSlow(offset);

        /// <summary>Code unit <paramref name="index"/> (of <paramref name="unit"/> bytes) from the token start, or -1 if incomplete.</summary>
        public int PeekUnit(int index, int unit, bool bigEndian)
        {
            int o = index * unit;
            if (PeekByte(o + unit - 1) == -1) return -1;
            return LexerRuntime.ReadUnit(_buf, _start + o, unit, bigEndian);
        }

        public bool StartsWith(byte[] prefix)
        {
            if (prefix.Length == 0) return false;
            for (int k = 0; k < prefix.Length; k++) if (PeekByte(k) != prefix[k]) return false;
            return true;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        int PeekSlow(int offset)
        {
            while (_start + offset >= _end)
            {
                if (_eof) return -1;
                Fill();
            }
            return _buf[_start + offset];
        }

        void Fill()
        {
            if (_end == _buf.Length)
            {
                if (_start == 0)
                {
                    Array.Resize(ref _buf, _buf.Length * 2);
                }
                else
                {
                    int count = _end - _start;
                    Array.Copy(_buf, _start, _buf, 0, count);
                    _start = 0;
                    _end = count;
                }
            }
            int n = _stream.Read(_buf, _end, _buf.Length - _end);
            if (n == 0) _eof = true;
            else _end += n;
        }

        public void Skip(int length) => _start += length;

        public string Take(int length, Encoding encoding)
        {
            string s = encoding.GetString(_buf, _start, length);
            _start += length;
            return s;
        }
    }
}
